---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}-headless
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.headless.annotations }}
  annotations:
{{ toYaml .Values.headless.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.headless.type }}
  clusterIP: None
  ports:
{{- if .Values.properties.clusterSecure }}
  - port: {{ .Values.properties.httpsPort }}
    name: https
{{- else}}
  - port: {{ .Values.properties.httpPort }}
    name: http
{{- end }}
  - port: {{ .Values.properties.clusterPort }}
    name: cluster
  selector:
    app: {{ include "apache-nifi.name" . | quote }}
    release: {{ .Release.Name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  {{- if eq .Values.service.type "NodePort" }}
    type: {{ .Values.service.type }}
    ports:
    - name: external-broker
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.extport }}
      nodePort: {{ .Values.service.nodeport }}
      protocol: TCP
    selector:
      app: {{  template "apache-nifi.name" .  }}
      release: {{ .Release.Name }}
      
  {{- end }}

