
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nifi-test
    meta.helm.sh/release-namespace: nifi-test
  creationTimestamp: "2021-02-25T12:46:31Z"
  labels:
    app: nifi
    app.kubernetes.io/managed-by: Helm
    chart: nifi-0.6.2
    heritage: Helm
    release: nifi-test
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":7001,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":7002,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:release: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2021-02-25T16:18:16Z"
  name: nifi-test
  namespace: nifi-test
  resourceVersion: "87498362"
  selfLink: /api/v1/namespaces/nifi-test/services/nifi-test
  uid: ebab0a25-3020-42e4-a910-83b874ab0e5f
spec:
  clusterIP: 10.233.47.236
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 8100
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nifi
    release: nifi-test
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

