apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-data-nifi-test-zookeeper-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-nifi-test-zookeeper-0
    namespace: nifi-test
  hostPath:
    path: /var/lib/docker/pv/vol-data-nifi-test-zookeeper-0
    type: ""
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  
status:
  phase: Bound
